[package]
name = "leptos-lucide-icons"
version = "0.1.0"
edition = "2021"
description = "Lucide icons ported over to Leptos"
license = "MIT"
homepage = "https://github.com/Alpyg/leptos-lucide-icons"
repository = "https://github.com/Alpyg/leptos-lucide-icons"

[dependencies]
